navikt/tms-min-side

server/server.js

Setter opp cors allowed origin som kan hentes fra secrets.

Setter opp cors allowed origin

---

mock/endpoint.js
package-lock.json
package.json
src/api/api.js
src/components/Authentication.jsx
src/renderApp.jsx
src/renderAppInDevelopment.jsx
src/urls.js
src/utils/redirect.js
vite.config.js

- Satt opp autentisering via IdPorten
- Satt opp lokal mocking for autentisering

Redirect etter autentisering

---

index.development.html
index.html
nais/dev-gcp/nais.yaml
nais/prod-gcp/nais.yaml
server.production.js
src/App.jsx
src/api/environment.jsx
src/api/redirect.jsx
src/components/errorboundary/ErrorBoundary.jsx
src/store/withStore.jsx

* Endrer ingresser til å peke på www.dev.nav.no og www.nav.intern.nav.no
* Fikser en bug i ErrorBoundary som kræsjet siden

PB.993: Endrer ingresser 

---

package-lock.json
src/components/authentication/Authentication.jsx

Denne ble trigget da man forsøkte å gå via loginservice og kallet mot oppfølging feilet med 401

Fjerner feilmeldingen under innlasting av siden

---

src/components/layout/Layout.jsx

, da innholdet ikke tilbys på andre spraak enn norsk per dags dato.
Etterspurt av team nav.no

Fjernet visningen av spraakvelgeren

---

package-lock.json
package.json
src/amplitude/amplitude.js
src/main.jsx
src/micro-frontend/MinSide.jsx

Lagt inn logging av hvilke brukere som får Aia-modul

Amplitude aia

---

src/urls.jsx

Bytter url til en ny backend for Arbeidsflate for innlogget arbeidssøker.

Oppdaterer til ny url av aia-backend

---

src/App.jsx
src/mikrofrontend/Arbeidssoker.jsx
src/mikrofrontend/MinSide.jsx
src/mikrofrontend/MinSideVarslinger.jsx

Dette gir oss mer fleksibilitet i overgangen til nyere bakgrunnsfarger

Setter sidemal for hver vertikale mikrofrontend

---

src/mikrofrontend/Utkast.jsx

Skal kun berøre fargen for brødsmulestien for tms-utkast-mikrofrontend til hvit, mens de andre sidene beholder den i grå.

Endret bakgrunnsfarge på brødsmuler for utkast siden.

---

src/App.jsx
src/components/layout/Layout.jsx
src/hooks/useLanguage.jsx
src/language/text.jsx

Språk spesifiseres enten i url(eks. ...minside/en/utkast) eller ved manuell endring i språkvelger fra dekoratøren.
Spesifisert språk lagres i sessionStorage og er tilgjengelig for MF, språkendring kommuniseres til MF med event.

Lagt inn språkhåndtering

---

nais/dev-gcp/nais.yaml
nais/prod-gcp/nais.yaml

Legg til domenene til dekoratøren i outbound policies.

Dev test access

---

.github/workflows/build-and-deploy.yaml
Dockerfile
importmap.json
package-lock.json
package.json
vite.config.js

Forenkler Vite config og oppdaterer til Node.js 18.15.0 (LTS).

Forenkler Vite config

---

src/components/dokumentarkiv/dokumenter/Dokumenter.tsx

Bruker credentials include på kall mot apier som ligger på andre origins

Bruker credentials include

---

src/components/loader/ContentLoader.module.css
src/components/loader/ContentLoader.tsx
src/mikrofrontends/arbeidssoker/Aia.tsx

Midlertidig fiks som fjerner unødvendige content loaders.

Fjerner unødvendig loader

---

src/mikrofrontends/utkast/Utkast.tsx

Endrer bakgrunnsfargen for containeren til brødsmulesti og språkvelger på undersiden for utkast til grå.

Bakgrunnsfarge brødsmulesti utkast

---

src/pages/[lang]/index.astro
src/pages/_index.module.css
src/pages/index.astro

Dette var en midlertidig løsning for oversikt som ikke trengs lenger.

Fjerner min-height for oversikt

---

src/components/dokumentarkiv/dokumentarkivUrls.ts

Endret url som brukes i dokumentarkiv-widget fra /mine-saker til /dokumentarkiv

Endret url fra /mine-saker til /dokumentarkiv

---

src/components/oversikt/din-oversikt/DinOversikt.tsx

Fjerner unødvendig fetcher som ikke trengs siden det allerede ligger i utils.

Fjerner unødvendig fetcher

---

mock/data/selector.json
src/components/oversikt/DinOversikt.tsx
src/components/oversikt/microfrontendTypes.tsx
src/components/oversikt/urls.ts
src/hooks/useLogComposition.ts
src/hooks/useOversikt.ts
src/utils/oversikt.ts

depends on navikt/tms-mikrofrontend-selector/pull/35

Personalized content

---

mock/data/selector.json
mock/server.ts
src/components/aktuelt/Aktuelt.module.css
src/components/aktuelt/Aktuelt.tsx
src/language/aktuelt.ts
src/pages/[lang]/index.astro
src/pages/index.astro

Hittil har vi lagt inn CSS kun til null eller én Widget

Lagge inn seksjon for Aktuelt

---

src/components/innboks/InnboksContent.tsx
src/components/obersvability/Observability.tsx
src/pages/[lang]/index.astro
src/pages/index.astro

Egen komponent for observability som gjør det enklere å debugge feil.

Egen komponent for observability

---

src/components/authentication/Authentication.tsx
src/layouts/base/Layout.astro
src/pages/[lang]/index.astro
src/pages/index.astro

Reload ved page transition for å unngå at browser viser cachet innhold

Reload ved page transition

---

src/mikrofrontends/arbeidssoker/Bekreftelse.tsx
src/mikrofrontends/arbeidssoker/urls.ts
src/pages/[lang]/arbeidssoker/bekreftelse.astro
src/pages/[lang]/arbeidssoker/index.astro
src/pages/arbeidssoker.astro
src/pages/arbeidssoker/[...path].astro

Setter opp en ny side på /arbeidssoker/bekreftelse som viser aia-meldekort

Ny side på /arbeidssoker/bekreftelse

---

package-lock.json
package.json

Oppdaterer Astro slik at det blir mulig å teste Server Islands i experimental mode.

Oppdaterer astro

---

src/components/oversikt/urls.ts
src/utils/client/environment.ts

Håndteringen av ansatt URLer kan gjøres på en bedre måte, men jeg tar det i en annen Pull request.

Midlertidig ansatt url for meldekort

---

.astro/settings.json
package-lock.json
src/components/dokumenter/dokumenter.astro
src/components/login-level-info/LoginLevelInfo.astro
src/components/substantial-info/SubstantialInfo.astro
src/env.d.ts
src/language/substantialInfo.ts
src/middleware/index.ts
src/pages/[lang]/index.astro
src/pages/index.astro

- **check acr**
- **debugging**
- **Debugging**
- **Add conditional rendering to dokumenter basert på security**
- **Add conditional rendering to dokumenter basert på security**
- **Vis info om innloggingsnivå**
- **Provide info regarding idporten-loa state**
- **reinstall node_modules**
- **Redirect to correct url for re-login**
- **Wrap description in a BodyShort**

Provide information about security login level

---

src/layouts/base/Layout.astro

Legg inn umami script

---

.astro/settings.json
.astro/types.d.ts
package-lock.json
package.json
src/components/oversikt/DinOversikt.module.css
src/components/oversikt/DinOversikt.tsx
src/components/oversikt/MicrofrontendWrapper.module.css
src/components/oversikt/MicrofrontendWrapper.tsx
src/components/oversikt/produktkort/Produktkort.module.css

Gjort om masonry layout i "din oversikt" til å bruke css only. 
Krevde også egen css i microfrontendwrapper og margin-bottom på produktkort

implementert masonry via css only
